### ISSUE TITLE
Does not work with node 0.12.7

### ISSUE THREAD

**Issue by matthewconstantine** [machty/ember-maybe-import-regenerator#1]
Getting this error when running an app using ember-concurrency on node 0.12.7:

```
Unexpected strict mode reserved word
.../node_modules/ember-concurrency/node_modules/ember-maybe-import-regenerator/index.js:14
    let hostApp = this._findApp(app);
    ^^^
SyntaxError: Unexpected strict mode reserved word
```

Any chance you could remove the `let` keyword for some backwards compatibility? We're getting some broken builds and can't easily upgrade our node version to support this.

**Comment by machty** [comment]
Sorry bout that, closed by #2, released in 0.1.3

**Comment by matthewconstantine** [comment]
Thanks!

**Comment by machty** [comment]
Also pushed 0.7.6 of e-c
