### ISSUE TITLE
Deprecation warning through used dependency

### ISSUE THREAD

**Issue by Yelinz** [machty/ember-maybe-import-regenerator#11]
`ember-maybe-import-regenerator > broccoli-funnel > exists-sync@0.0.4: Please replace with usage of fs.existsSync`

This can be fixed by updating the broccoli-funnel version

**Comment by SergeAstapov** [comment]
`broccoli-funnel` has been updated on master.

@machty do you mind to release new version?

**Comment by stefanpenner** [comment]
we will release shortly
