### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by kellyselden** [machty/ember-maybe-import-regenerator#26]
I'd like a starting Ember app to not have any pre 1.0 deps in the package.json. Can we bump to 1.0?

**Comment by knownasilya** [comment]
Would love to see master released.

**Comment by mydea** [comment]
I am getting deprecation warnings for this addon using ember-cli-babel v6.x now - I guess one more reason why it would be great to cut a release from master :)

**Comment by knownasilya** [comment]
Would love to see this released 👍🏼

**Comment by stefanpenner** [comment]
I'll cut 1.0.0 shortly
