### ISSUE TITLE
Use of older ember-cli-babel results in ember-global deprecation with ember-source 3.27.x

### ISSUE THREAD

**Issue by runspired** [machty/ember-maybe-import-regenerator#34]

**Comment by NullVoxPopuli** [comment]
I just ran in to this, too

**Comment by alexlafroscia** [comment]
Without an `addon` or `app` tree, the dependency of `ember-cli-babel` doesn't even do anything, right? Could it just be removed entirely?

**Comment by stefanpenner** [comment]
fixed on master.... I am planning a release shortly.
