### ISSUE TITLE
Which apps still need this addon?

### ISSUE THREAD

**Issue by st-h** [machty/ember-maybe-import-regenerator#36]
Sorry about the strange question, but I installed this addon long time ago and can't fully remember why it even was necessary. Do we still need this addon in modern (up-to-date) ember apps? I just tried and everything seems to run fine... Does it depend on the browser version used?

**Comment by charlesfries** [comment]
It's installed by default when you run `ember new`

**Comment by st-h** [comment]
Yeah, that might be. However, when I started that app, that hasn't been the case and I added it manually later. I've been looking a bit into this. If I didn't miss anything, the regenerator runtime mostly is needed for browsers that do not support async functions natively, correct? https://caniuse.com/async-functions

src: https://stackoverflow.com/questions/65378542/what-is-regenerator-runtime-npm-package-used-for

**Comment by NullVoxPopuli** [comment]
I'd also like guidance on this -- I've found that most of my projects don't need this addon, but some fail, and I don't know why / what the difference is. :-\

**Comment by stefanpenner** [comment]
I believe it exists for IE11 users who use async/await or generators.

**Comment by ctjhoa** [comment]
@stefanpenner Sorry to go back later on this but from my understanding this addon should be useless.

`ember-cli-babel` relies on `babel-preset-env` and [babel-plugin-transform-regenerator](https://babeljs.io/docs/en/babel-plugin-transform-regenerator) is included in `@babel/preset-env`

So using Ember `config/targets.js` should already drive babel configuration to transpile (or not) generators.
Am I missing something?

**Comment by ctjhoa** [comment]
Looks like it's because ember-cli-babel still rely on [babel-polyfill](https://babeljs.io/docs/en/babel-polyfill/) (https://github.com/babel/ember-cli-babel/issues/298)
