### ISSUE TITLE
Reliance on the `Promise` global makes this fail in Phantom (and possible IE)

### ISSUE THREAD

**Issue by cibernox** [machty/ember-maybe-import-regenerator#6]
I've just discovered due to [this bug report](https://github.com/cibernox/ember-power-select/issues/933) that the regenerator runtime depends on the existence of a global `Promise`.

```js
  function _asyncToGenerator(fn) {
    return function () {
      var gen = fn.apply(this, arguments);
      return new Promise(function (resolve, reject) { // <=== here!
        function step(key, arg) {
          try {
            var info = gen[key](arg);
            var value = info.value;
          } catch (error) {
            reject(error);
            return;
          }

          if (info.done) {
            resolve(value);
          } else {
            return Promise.resolve(value).then(function (value) {
              step("next", value);
            }, function (err) {
              step("throw", err);
            });
          }
        }

        return step("next");
      });
    };
  }
```

While this is not directly related with this addon but with the polyfill, I wonder how come the polyfill is supported to work in IE. Perhaps there should be an `ember-maybe-import-promise`?

**Comment by amk221** [comment]
I think this is related: 
https://github.com/emberjs/ember-qunit/issues/300
https://github.com/amk221/-ember-new-qunit-tests/pull/1#issuecomment-352277086

**Comment by joe-wroten-q2** [comment]
Encountered this issue in IE11. Solution we went with was adding the following code to `app.js`.

```javascript
import RSVP from 'rsvp';

if (!window.Promise) {
  window.Promise = RSVP.Promise;
}
```

**Comment by stefanpenner** [comment]
I don't believe this is still an issue. If a reproduction can be provided, we can gladly reopen.
