### ISSUE TITLE
How to install in an existing app?

### ISSUE THREAD

**Issue by gnapse** [machty/ember-maybe-import-regenerator#8]
Forgive my ignorance, but the installation instructions in the README of this repo do not look like they're meant to install this addon in an existing application. They say we should clone the repo and do npm and bower install in it. But how do I get my ember-cli app to use this?

**Update:**

Wouldn't it be something like this?

```
ember install ember-maybe-import-regenerator
```

Perhaps that's what the README should mention about installing this addon.

**Comment by stefanpenner** [comment]
you are correct, readme is updated now :)
