### ISSUE TITLE
Failing with Ember CLI 3.5

### ISSUE THREAD

**Issue by jherdman** [machty/ember-maybe-import-regenerator#9]
I'm seeing this error since upgrading to ember cli 3.5:

Cannot read property 'isPluginRequired' of undefined

e.g. https://travis-ci.org/PrecisionNutrition/unit-utils/jobs/442373632

**Comment by wei-qiu** [comment]
I got the same issue, then i run command:  "ember install ember-cli-babel", the issue is resolved. Hopefully this is helpful.

**Comment by stefanpenner** [comment]
It appears to be currently working ok. If there are steps to reproduce still, please share and reopen this issue.
